# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Sanitizers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  asan:
    name: AddressSanitizer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build clang

      - name: Test with ASan
        env:
          CC: clang
        run: ./scripts/ci/sanitizers.sh address

  ubsan:
    name: UndefinedBehaviorSanitizer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build clang

      - name: Test with UBSan
        env:
          CC: clang
        run: ./scripts/ci/sanitizers.sh undefined
