# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Sanitizers

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'include/**'
      - 'test/**'
      - 'sql/**'
      - '*.control'
      - 'meson.build'
      - 'VERSION'
      - 'meson_options.txt'
      - 'scripts/ci/sanitizers.sh'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'include/**'
      - 'test/**'
      - 'sql/**'
      - '*.control'
      - 'meson.build'
      - 'VERSION'
      - 'meson_options.txt'
      - 'scripts/ci/sanitizers.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  asan:
    name: AddressSanitizer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build clang libgsl-dev \
            libopenblas-dev

      - name: Core dumps
        uses: ./.github/actions/coredumps

      - name: Test with ASan
        env:
          CC: clang
        run: ./scripts/ci/sanitizers.sh address

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: test-logs-asan
          path: builddir-san-address/meson-logs/
          retention-days: 7

  ubsan:
    name: UndefinedBehaviorSanitizer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build clang libgsl-dev \
            libopenblas-dev

      - name: Core dumps
        uses: ./.github/actions/coredumps

      - name: Test with UBSan
        env:
          CC: clang
        run: ./scripts/ci/sanitizers.sh undefined

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: test-logs-ubsan
          path: builddir-san-undefined/meson-logs/
          retention-days: 7
